# This is a basic workflow to help you get started with Actions
name: CI


on:
  push:
    branches: [main,activity,srp93]
  pull_request:
    branches: [main,activity,srp93] 
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
          python3 -m pip install --upgrade google-auth
          python3 -m pip install --requirement requirements.txt
      - name: Fixing Python file with Pylint
        run: |
<<<<<<< HEAD
          python3 -m pylint -d E1101,C0413,W1508,R0903,W0603,W0611,R1702,R1705 $(find ./ -type f | grep '.py$' | xargs)
=======
          python3 -m pylint -d E1101,C0413,W1508,R0903,W0603,W0611,R1705,R1702 $(find ./ -type f | grep '.py$' | xargs)
>>>>>>> ae18d69a3e1be7be8d8f6d266646aeb964a829d7
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
      - name: fixing JS file with eslint
        run: |
          npx eslint src/ --ext js,jsx
