# This is a basic workflow to help you get started with Actions
name: CI


on:
  push:
    branches: [main,activity,srp93,unmocked_tests]
  pull_request:
    branches: [main,activity,srp93,unmocked_tests] 
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
          python3 -m pip install --upgrade google-auth
          python3 -m pip install --requirement requirements.txt
      - name: Fixing Python file with Pylint
        run: |
          python3 -m pylint -d W0611,C0413,E0401,E1101,R0401,R0903,W1508,W0603 $(find ./ -type f | grep '.py$' | xargs)
      - name: Run unit tests
        run: |
<<<<<<< HEAD
          python tests/mocked/unit_tests.py
=======
          python mocked_unit_tests.py
>>>>>>> 74a523dd4a26cb110394c4bbf9c1c829c23931b4
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
      - name: fixing JS file with eslint
        run: |
          npx eslint src/ --ext js,jsx
